brew "antigen"

brew "neovim"
brew "ansible"
brew "direnv"
brew "tig"
brew "nmap"
brew "httpie"
brew "graphviz"
brew "tmux"
brew "golang"
brew "jq"
brew "aria2"
brew "ag"
brew "rbenv"
brew "node@8"
brew "fzf"
brew "kubectx"
brew "stern"
brew "kubectl"
brew "highlight"
brew "fd"
brew "rg"
brew "kubernetes-helm"
brew "watch"
brew "redis"
brew "consul"
brew "pgcli"
brew "cmake"
brew "python3"
brew "htop"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "telnet"
brew "fswatch"
brew "tldr"
brew "bitwarden-cli"
brew "hugo"
brew "tokei"
brew "bat"
brew "prettyping"
brew "diff-so-fancy"
brew "exa"
brew "ngrep"
brew "jid"
brew "gpg"
brew "dep"
brew "websocketd"
brew "unrar"
brew "speedtest-cli"
brew "bats"
brew "rust"
brew "terraform"

tap "thecasualcoder/stable"

brew "tztail"
brew "kube-fzf"
brew "kube-tmuxp"
brew "lazy-connect"

tap "goreleaser/tap"
brew "goreleaser"

tap "wagoodman/dive"
brew "dive"

tap "reactiveops/tap"

brew "rbac-lookup"

tap "koekeishiya/formulae"

brew "chunkwm"
brew "skhd"

tap "caskroom/cask"

cask "firefox"
cask "iterm2"
cask "visual-studio-code"
cask "google-chrome"
cask "ngrok"
cask "flux"
cask "slack"
cask "spectacle"
cask "caffeine"
cask "openoffice"
cask "vagrant"
cask "rowanj-gitx"
cask "vlc"
cask "clipy"
cask "google-cloud-sdk"
cask "kindle"
cask "postman"
cask "minikube"
cask "vimr"
cask "docker"
cask "grammarly"
cask "gitter"
cask "discord"
cask "xca"
cask "whatsapp"
cask "virtualbox"
cask "sketch"
cask "steam"
cask "android-file-transfer"
cask "charles"
cask "tipp10"
cask "rowanj-gitx"
cask "balenaetcher"
cask "licecap"
cask "java"
cask "google-backup-and-sync"
cask "keybase"
cask "keycastr"
cask "bitwarden"
cask "alacritty"
cask "notion"
cask "sloth"
cask "netspot"
cask "station"
cask "adoptopenjdk8"
cask "android-studio"

tap "caskroom/fonts"
cask "font-fira-code"
