#!/usr/bin/env zsh

# zsh config files can be compiled to improve performance
# Copied from: https://github.com/romkatv/zsh-bench/blob/master/configs/ohmyzsh%2B/setup

# https://gist.github.com/vraravam/76880d9ab0f355bfc521eaf23efc9d6e


echo "Starting compile"

for f in ${ZSH}/{oh-my-zsh.sh,**/*.zsh}; do
  echo "compiling $f"
  zcompile -R -- "$f".zwc "$f" 1>/dev/null
done

echo "Ended compile"
