#!/bin/bash

set -e

trackpad_settings() {
    # speed
    defaults write NSGlobalDomain com.apple.trackpad.scaling 3
    
    # tap to click
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior 1
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking 1
    defaults write com.apple.AppleMultitouchTrackpad Clicking 1
}

keyboard_settings() {
    # use F1, F2, etc. as standard function keys
    defaults write NSGlobalDomain com.apple.keyboard.fnState 1
}

apply_osx_defaults() {
    trackpad_settings
    keyboard_settings
    /System/Library/PrivateFrameworks/SystemAdministration.framework/Resources/activateSettings  -u
}

apply_osx_defaults
