#!/usr/bin/env bash

set -e

op_account=$(op account list --format json | jq -r '.[] | select(.email == "arunvelsriram@gmail.com") | .account_uuid')
password=$(op --account ${op_account} read 'op://Private/Raycast Settings/password')

open  raycast://extensions/raycast/raycast/import-settings-data

osascript <<EOF
  tell application "System Events"
    key code 36
    delay 0.3
    
    key code 5 using {command down, shift down}
    delay 0.3
    
    keystroke "~/dotfiles/Raycast.rayconfig"
    delay 0.3

    key code 36
    delay 0.5

    key code 36
    delay 0.3

    keystroke "${password}"
    key code 36
    delay 0.3

    key code 36
    delay 0.3

    key code 36
    delay 2

    key code 53
    key code 53
  end tell
EOF
