#!/usr/bin/env bash

set -e

op_account=$(op account list --format json | jq -r '.[] | select(.email == "arunvelsriram@gmail.com") | .account_uuid')
password=$(op --account ${op_account} read 'op://Private/Raycast Settings/password')

osascript <<EOF
  do shell script "open  'raycast://extensions/raycast/raycast/export-settings-data'"
  
  tell application "System Events"
    key code 36
    delay 0.3

    if (static text "Enter password" of window 1 of application process "Raycast") exists then
		  keystroke "${password}"
      delay 0.3

      key code 36
      delay 0.3

      keystroke "${password}"
      delay 0.3

      key code 36
      delay 0.3
    end if
    
    key code 5 using {command down, shift down}
    delay 0.3
    
    keystroke "~/dotfiles/"
    delay 0.3
    
    key code 36
    delay 0.3

    key code 36
    delay 0.5

    key code 53
  end tell
EOF

rm ~/dotfiles/Raycast.rayconfig
mv ~/dotfiles/Raycast*.rayconfig ~/dotfiles/Raycast.rayconfig
