#!/bin/bash

FILES=(bashrc bash_profile profile zshrc gitconfig gemrc vimrc oh-my-zsh/custom/aliases.zsh oh-my-zsh/custom/tw_digital.zsh)
BACKUP_DIR=~/dotfiles.backup.`date +%-H-%M-%S-%F`

create_directories() {
  mkdir -p $BACKUP_DIR
  mkdir -p $BACKUP_DIR/oh-my-zsh/custom
}

backup() {
  for file in ${FILES[@]}; do
    full_path=~/.$file
    cp $full_path $BACKUP_DIR/$file
  done

  echo Copied existing files to $BACKUP_DIR
  echo
}

setup() {
  for file in ${FILES[@]}; do
    full_path=~/.$file
    rm $full_path
    ln -sv ~/dotfiles/$file $full_path
  done
}

create_directories
backup
setup